"""Generate RULES_TRACEABILITY.md from the codebase (reproducible, no guesses).

Three maps, all derived from the actual code/tests/card data:

1. Cards (74 x both faces): for every card, classify how its Event and Capability
   faces are implemented (which registry/handler) and whether any test references
   the card -- by id OR by effect/title keyword. A card with neither id nor
   keyword in tests/ is flagged UNTESTED.

2. Rule clauses: every Plantagenet rule number cited in src/ (the developers
   annotated handlers with the rule they implement), with the modules citing it
   and the test files that cite the same number. NOTE: a test may exercise a
   clause without writing its number, so a blank test column is a LOWER bound,
   not proof of no test -- unlike the card map, which also matches by keyword.

3. Forward traceability: the authoritative clause index extracted from the
   Rules of Play PDF (source/plantagenet_clause_index.tsv, regenerated by
   scripts/extract_clause_index.py) is checked against the clauses cited in
   src/; rulebook clauses with no citation anywhere in their chain (self,
   ancestor, or descendant) are listed as candidates for gap review.

(A 2026-06-22 session note claimed the repo's Rules PDF was the Seljuk series
rulebook. That was wrong -- the PDF is the Plantagenet Rules of Play (L&C
Vol. IV); see SMOKE_TEST_FINDINGS.md round 2026-07-01. The correct PDF is what
makes map 3 possible.)
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

sys.path.insert(0, "src")
from plantagenet import events, ratings, reactions, static_data

# effect/title keywords per card so a behaviour test counts even without the id
KEYWORDS = {
    "Y36": ["swift_maneuver", "vanguard"], "L6": ["great_ships", "seamanship"],
    "L8": ["hay_wains", "forced_march"], "Y29": ["dorset", "stafford_branch"],
    "L22": ["french_troops", "stafford_estates"],
    "L29": ["high_admiral", "wilful", "disobedience"],
    "L37": ["richmond", "madame", "earl_of_richmond"],
}


def _grep_files(pattern, path):
    out = subprocess.run(["grep", "-rilE", pattern, path],
                         capture_output=True, text=True).stdout
    return sorted(f.split("/")[-1] for f in out.split("\n")
                  if f and "__pycache__" not in f and "/data" not in f)


def card_rows():
    cards = static_data.load_cards()
    immediate = set(getattr(events, "_IMMEDIATE", {}))
    persist = set(getattr(events, "_PERSIST", set()))
    held = set(getattr(events, "_HELD_PLAYS", {}))
    battle_rx = set(getattr(reactions, "BATTLE_REACTIONS", {}))
    cap_titles = set(getattr(ratings, "_CAP_RATING_MODS", {}))
    battle_caps = set(getattr(reactions, "_BATTLE_CAPS", {}))
    ev_titles = {"RICHARD OF YORK", "PRIVY COUNCIL", "YORKIST PARADE",
                 "LOYALTY AND TRUST", "EDWARD V"}
    rows = []
    for cid in sorted(cards, key=lambda x: (x[0], int(x[1:]))):
        cd = cards[cid]
        ev, cap = cd.get("event") or {}, cd.get("capability") or {}
        eimpl = []
        if cid in immediate:
            eimpl.append("immediate")
        if cid in persist:
            eimpl.append("persist")
        if cid in held:
            eimpl.append("held")
        if cid in battle_rx:
            eimpl.append("battle-reaction")
        if ev.get("title") in ev_titles:
            eimpl.append("event-rating-mod")
        cimpl = []
        if cap.get("title") in cap_titles:
            cimpl.append("rating-mod")
        if cap.get("title") in battle_caps:
            cimpl.append("battle-cap")
        code = _grep_files(rf"\b{cid}\b", "src/plantagenet")
        if not eimpl and not cimpl and code:
            eimpl.append("code")
        pat = "|".join([rf"\b{cid}\b"] + KEYWORDS.get(cid, []))
        tests = _grep_files(pat, "tests")
        rows.append((cid, cd["side"], ev.get("title", ""), cap.get("title", ""),
                     "+".join(eimpl) or "-", "+".join(cimpl) or "-", tests))
    return rows


def clause_index():
    """clause -> title from the committed rulebook index (empty if absent)."""
    idx = {}
    try:
        lines = open("source/plantagenet_clause_index.tsv").read().splitlines()
    except FileNotFoundError:
        return idx
    for line in lines:
        if line.startswith("#") or "\t" not in line:
            continue
        clause, title = line.split("\t", 1)
        idx[clause] = title
    return idx


def uncovered_clauses(idx, cited):
    """Rulebook clauses with no citation of self, ancestor, or descendant."""
    def covered(c):
        if c.endswith(".0"):  # section header: any citation in the section
            return any(s.startswith(c[:-1]) for s in cited)
        return any(s == c or s.startswith(c + ".") or c.startswith(s + ".")
                   for s in cited)
    return [(c, idx[c]) for c in
            sorted(idx, key=lambda r: [int(x) for x in r.split(".")])
            if not covered(c)]


def rule_rows():
    rule = re.compile(r'(?<![\d.])(\d\.\d{1,2}(?:\.\d{1,2})?)(?![\d])')
    src, tst = {}, {}
    for root, store in (("src/plantagenet", src), ("tests", tst)):
        for dp, _, fs in os.walk(root):
            if "__pycache__" in dp or "/data" in dp:
                continue
            for fn in fs:
                if not fn.endswith(".py"):
                    continue
                for line in open(os.path.join(dp, fn), errors="ignore"):
                    for m in rule.findall(line):
                        if 1 <= int(m.split(".")[0]) <= 7:
                            store.setdefault(m, set()).add(fn)
    rules = sorted(set(src) | set(tst), key=lambda r: [int(x) for x in r.split(".")])
    return [(r, sorted(src.get(r, [])), sorted(tst.get(r, []))) for r in rules], src, tst


def main():
    cards = card_rows()
    rules, src, tst = rule_rows()
    untested = [r for r in cards if not r[6]]
    idx = clause_index()
    gaps = uncovered_clauses(idx, set(src)) if idx else []
    out = ["# Rules Traceability Matrix",
           "",
           "_Generated by `scripts/build_traceability.py` from the code, tests, and "
           "card data — re-run after changes._",
           "",
           "## Summary",
           "",
           f"- Arts of War cards: **{len(cards)}** (37 per side), both faces classified.",
           f"- Cards with no test (by id or effect keyword): **{len(untested)}** "
           f"({', '.join(r[0] for r in untested) or 'none'}).",
           f"- Distinct rule clauses cited in code: **{len(src)}**; "
           f"clauses also cited by number in tests: **{len(tst)}**.",
           f"- Rulebook clauses (index extracted from the Rules of Play PDF): "
           f"**{len(idx)}**; with no code citation in their chain: **{len(gaps)}**.",
           "",
           "> A blank test column in the rule table is a lower bound — behaviour "
           "may be tested without citing the clause number. The card table also "
           "matches by effect keyword, so its UNTESTED flags are reliable. The "
           "last section is forward traceability: the rulebook's own clause "
           "list checked against the code.",
           "",
           "## Arts of War cards (74 × both faces)",
           "",
           "| Card | Side | Event face | Event impl | Capability face | Cap impl | Tests |",
           "|------|------|-----------|-----------|-----------------|----------|-------|"]
    for cid, side, ev, cap, ei, ci, tests in cards:
        tcell = ", ".join(t.replace("test_", "").replace(".py", "") for t in tests) \
            if tests else "**UNTESTED**"
        out.append(f"| {cid} | {side[:4]} | {ev} | {ei} | {cap} | {ci} | {tcell} |")
    out += ["", "## Rule clauses cited in code", "",
            "| Clause | Implemented in | Tests citing clause |",
            "|--------|----------------|---------------------|"]
    for r, s, t in rules:
        out.append(f"| {r} | {', '.join(x.replace('.py','') for x in s) or '-'} "
                   f"| {', '.join(x.replace('test_','').replace('.py','') for x in t) or '—'} |")
    out += ["", "## Rulebook clauses with no code citation (forward traceability)",
            "",
            "Clauses from `source/plantagenet_clause_index.tsv` with no citation "
            "in src/ of the clause itself, an ancestor, or a descendant. Review "
            "each: rules gap, or descriptive-only clause needing no code.",
            "",
            "| Clause | Title |",
            "|--------|-------|"]
    out += [f"| {c} | {t} |" for c, t in gaps] or ["| — | none |"]
    open("RULES_TRACEABILITY.md", "w").write("\n".join(out) + "\n")
    print(f"wrote RULES_TRACEABILITY.md: {len(cards)} cards, {len(rules)} clauses "
          f"cited, {len(untested)} untested cards, {len(gaps)}/{len(idx)} "
          f"rulebook clauses uncited")


if __name__ == "__main__":
    main()
