"""Extract the authoritative clause index from the Plantagenet Rules of Play PDF.

Writes source/plantagenet_clause_index.tsv (clause number TAB title), the input
for forward traceability in scripts/build_traceability.py. Requires pdftotext
(poppler-utils). The TSV is committed so the build script never needs the PDF.

Extraction is done twice (reading-order and -layout modes) and unioned, because
each mode drops headings the other catches in the two-column layout. Warnings
are printed for numbering holes (e.g. 3.4.4 missing while 3.4.5 exists) and for
clauses extracted with conflicting titles -- eyeball those against the PDF.
"""

from __future__ import annotations

import collections
import re
import subprocess
import sys
import tempfile

PDF = "source/Plantagenet_Rules_Final_web.pdf"
OUT = "source/plantagenet_clause_index.tsv"

# heading = clause number at line start (any indent; some headings carry a
# private-use ornament glyph, e.g. \uf075, from the PDF font), then a
# capitalised title ending at the first period/colon or end of line.
# Cross-references are followed by ')' ',' or a lowercase word and never match.
HEAD = re.compile(r"^[\s\u2022\uf000-\uf8ff]*([1-6]\.\d{1,2}(?:\.\d{1,2})?)\.?\s+"  # \.? = the "3.4.1. Parley" typo in the PDF
                  r"([A-Z][A-Za-z0-9'’\- /&,()]*?)\s*(?:[.:]\s|[.:]?\s*$)")


def _extract(mode_args):
    with tempfile.NamedTemporaryFile(suffix=".txt") as tf:
        subprocess.run(["pdftotext", *mode_args, PDF, tf.name], check=True)
        return open(tf.name, errors="ignore").read().splitlines()


def _key(clause):
    return [int(x) for x in clause.split(".")]


def main():
    found = collections.defaultdict(collections.Counter)
    for args in ([], ["-layout"]):
        for line in _extract(args):
            # -layout renders the two columns side by side; split on the
            # column gap so a heading sharing a line with the other column
            # still starts its own chunk
            chunks = re.split(r"\s{4,}", line) if args else [line]
            for chunk in chunks:
                m = HEAD.match(chunk)
                if m:
                    found[m.group(1)][m.group(2).strip()] += 1
    index = {}
    for clause, titles in found.items():
        best, _ = titles.most_common(1)[0]
        if len(titles) > 1:
            print(f"WARNING conflicting titles for {clause}: "
                  f"{dict(titles)} -> kept {best!r}", file=sys.stderr)
        index[clause] = best
    # numbering-hole check: within each parent, child n>1 implies child n-1
    for clause in sorted(index, key=_key):
        parts = _key(clause)
        if parts[-1] > 1:
            prev = ".".join(map(str, parts[:-1] + [parts[-1] - 1]))
            if prev not in index:
                print(f"WARNING numbering hole: {clause} present, {prev} "
                      f"missing -- check the PDF", file=sys.stderr)
    with open(OUT, "w") as f:
        f.write("# clause\ttitle  (generated by scripts/extract_clause_index.py "
                "from the Rules of Play PDF)\n")
        for clause in sorted(index, key=_key):
            f.write(f"{clause}\t{index[clause]}\n")
    print(f"wrote {OUT}: {len(index)} clauses")


if __name__ == "__main__":
    main()
